/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Apl_CuciKendaraan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Transaksi extends javax.swing.JFrame {

    private final int idPegawai;
    private final String namaPegawai;
    private final String aksesPegawai;
    /**
     * Creates new form Transaksi
     */
    public Transaksi(int id, String nama,String akses) {
        initComponents();
        
        this.idPegawai = id;
        this.namaPegawai = nama;
        this.aksesPegawai = akses;
        
        load_table();
    }

//    private void delete_layanan(){
//    Connection conn = KoneksiDatabase.configDB();
//    String deleteLayananSql = "DELETE FROM layanan WHERE ID = ?";
//    PreparedStatement pstDelete = conn.prepareStatement(deleteLayananSql);
//    pstDelete.setString(1, selectedIdLayananData); // Gunakan selectedIdLayananData
//    
//    pstDelete.executeUpdate();
//    }
    
    private void load_table() {
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Jenis Perawatan");
        model.addColumn("Ukuran Motor");
        model.addColumn("Harga");
        model.addColumn("Admin");

        // menampilkan data database ke dalam JTable
        try {
            String sql = "SELECT * FROM layanan";
            Connection conn = KoneksiDatabase.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString(1), 
                    res.getString(2), 
                    res.getString(3), 
                    res.getString(4), 
                    res.getString(5),
                    res.getString(6)
                });
            }
            jTable1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        selectedNamaPelanggan = new javax.swing.JLabel();
        selectedJenisPerawatan = new javax.swing.JLabel();
        selectedUkuranMotor = new javax.swing.JLabel();
        hargaDouble = new javax.swing.JLabel();
        selectedAdmin = new javax.swing.JLabel();
        selectedIdLayanan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Bayar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Uang");

        jLabel5.setText("Kembalian");

        jLabel6.setText("Rp.");

        jLabel7.setText("TRANSAKSI");

        jLabel8.setText("...");

        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Harga :");

        jLabel2.setText("Rp.");

        jLabel3.setText("0");

        jLabel9.setText("Id Layanan :");

        jLabel10.setText("Nama Pelanggan :");

        jLabel11.setText("Jenis Pelanggan :");

        jLabel12.setText("Ukuran Motor :");

        jLabel13.setText("Harga :");

        jLabel14.setText("Admin :");

        selectedNamaPelanggan.setText("...");

        selectedJenisPerawatan.setText("...");

        selectedUkuranMotor.setText("...");

        hargaDouble.setText("...");

        selectedAdmin.setText("...");

        selectedIdLayanan.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(selectedJenisPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectedNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectedIdLayanan))))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(110, 110, 110)
                                    .addComponent(hargaDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(110, 110, 110)
                                    .addComponent(selectedAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectedUkuranMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(148, 148, 148)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(selectedIdLayanan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(selectedNamaPelanggan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(selectedJenisPerawatan))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(selectedUkuranMotor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(hargaDouble))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(selectedAdmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.rowAtPoint(evt.getPoint());
//        
        String id = jTable1.getValueAt(baris, 0).toString();//Id
        selectedIdLayanan.setText(id);
//        
        String nama = jTable1.getValueAt(baris, 1).toString(); //Nama
        selectedNamaPelanggan.setText(nama);
        
        String jenis = jTable1.getValueAt(baris, 2).toString(); //JenisPerawatan
        selectedJenisPerawatan.setText(jenis);
//      
        String ukuran = jTable1.getValueAt(baris, 3).toString(); //Ukuran Motor
        selectedUkuranMotor.setText(ukuran);
        
        String harga = jTable1.getValueAt(baris, 4).toString(); //Harga
        hargaDouble.setText(harga);
        
        String nama_admin = jTable1.getValueAt(baris, 5).toString(); //Nama Admin
        selectedAdmin.setText(nama_admin);
        
        String hargaLabel = jTable1.getValueAt(baris, 4).toString();
        jLabel3.setText(hargaLabel);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           
    String hargaString = jLabel3.getText(); // Misal isinya "30000.00"
    
try {
    // Hapus karakter non-angka jika ada (misal "Rp. ", spasi, koma desimal jika menggunakan koma)
    hargaString = hargaString.replace("Rp. ", "").replace(",", ""); // Contoh: Menghapus "Rp. " dan koma ribuan jika ada

    double hargaDouble = Double.parseDouble(hargaString); // Parse sebagai double

    // Untuk uang pelanggan juga:
    String uangPelangganString = jTextField4.getText();
    uangPelangganString = uangPelangganString.replace(",", ""); // Hapus koma ribuan jika ada
    double uangPelangganDouble = Double.parseDouble(uangPelangganString);

    double kembalian = uangPelangganDouble - hargaDouble;
    String jumlahString = String.valueOf(kembalian);
    if (uangPelangganDouble == hargaDouble){
    // 1. Hapus JLabel dari JFrame (kontainer-nya)
    this.remove(jLabel6); // 'this' merujuk pada JFrame itu sendiri

    // 2. Set variabel label menjadi null (opsional tapi disarankan)
    jLabel6 = null;

    // 3. Beri tahu JFrame untuk menghitung ulang layout dan menggambar ulang
    this.revalidate();
    this.repaint();
        jLabel8.setText("Uangnya Pas");
    }else {
         jLabel8.setText(jumlahString);
                 }
    } catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error: Format harga atau uang tidak valid. Pastikan hanya angka dan titik desimal (jika ada).");
    e.printStackTrace();
    }   

    //Hapus database Layanan
    int selectedRow = jTable1.getSelectedRow();
    try {
                Connection conn = KoneksiDatabase.configDB();
                String idLayanan = jTable1.getValueAt(selectedRow, 0).toString();
                String NamaLayanan = jTable1.getValueAt(selectedRow, 1).toString();
                String JenisLayanan = jTable1.getValueAt(selectedRow, 2).toString();
                String UkuranLayanan = jTable1.getValueAt(selectedRow, 3).toString();
                String HargaLayanan = jTable1.getValueAt(selectedRow, 4).toString();
                String AdminLayanan = jTable1.getValueAt(selectedRow, 5).toString();
                String sqlHistory = "INSERT INTO history (id_layanan_asli,nama_pelanggan,jenis_perawatan,ukuran_motor,harga_layanan,admin_pelayan)VALUES (?,?,?,?,?,?)";
                PreparedStatement rst = conn.prepareStatement(sqlHistory);
                rst.setString(1, idLayanan);
                rst.setString(2, NamaLayanan);
                rst.setString(3, JenisLayanan);
                rst.setString(4, UkuranLayanan);
                rst.setString(5, HargaLayanan);
                rst.setString(6, AdminLayanan);
                
                rst.execute();
                
                String sql = "DELETE FROM layanan WHERE id_layanan=?";
                
                PreparedStatement pst = conn.prepareStatement(sql);
                
                pst.setString(1, idLayanan);
                
                pst.execute();
                JOptionPane.showMessageDialog(null, "Berhasil membayar");

                load_table();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data pegawai. Pastikan tidak ada data terkait di tabel lain.\n" + e.getMessage());
                e.printStackTrace();
            }// Ini akan menjalankan perintah DELETE
    
    load_table();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (this.aksesPegawai.equalsIgnoreCase("Admin")) {
            // Jika akses adalah Admin, buka DashboardAdmin
            new DashboardAdmin(this.idPegawai, this.namaPegawai, this.aksesPegawai).setVisible(true);
            this.dispose();  //ubah ke dashboard admin jika sudah jadi
        } else if (this.aksesPegawai.equalsIgnoreCase("Pegawai")) {
            // Jika akses adalah Pegawai, buka DashboardPegawai
            new DashboardPegawai(this.idPegawai, this.namaPegawai, this.aksesPegawai).setVisible(true); //ubah ke dashboard pegawai jika sudah jadi
            this.dispose();
        } else {
            // Jika ada level akses lain yang tidak terduga
            JOptionPane.showMessageDialog(this, "Hak akses Anda tidak dikenali!", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Hentikan proses
        }
//        new DashboardAdmim().setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Transaksi().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hargaDouble;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel selectedAdmin;
    private javax.swing.JLabel selectedIdLayanan;
    private javax.swing.JLabel selectedJenisPerawatan;
    private javax.swing.JLabel selectedNamaPelanggan;
    private javax.swing.JLabel selectedUkuranMotor;
    // End of variables declaration//GEN-END:variables
}
